server {
    listen 8080;           # Puerto donde Nginx escucha peticiones
    server_name _;         # Acepta cualquier dominio

    root /usr/share/nginx/html;   # Carpeta raíz donde están los archivos del sitio
    index index.html;             # Archivo que se sirve por defecto en "/"
}


#Es como el "mesero" que recibe las peticiones del navegador y le entrega los archivos de la página